use EVERTEC
GO

CREATE TABLE CIDADES(
	CODIGO int IDENTITY(1,1) PRIMARY KEY NOT NULL ,
	NOME nvarchar(100) NULL,
	ESTADO char(2) NULL,
	CEP_INICIAL char(8) NULL,
	CEP_FINAL char(8) NULL);
GO

CREATE TABLE CLIENTES(
	CODIGO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME NVARCHAR(100),
	CPF_CNPJ VARCHAR(14),
	TELEFONE VARCHAR(11),
	ENDERECO NVARCHAR(255),
	BAIRRO NVARCHAR(100),
	COMPLEMENTO NVARCHAR(50),
	EMAIL NVARCHAR(50),
	COD_CIDADE INT

	 CONSTRAINT FK_CLIENTES_CIDADES 
        FOREIGN KEY (COD_CIDADE) 
        REFERENCES CIDADES(CODIGO)

);
