USE EVERTEC
GO

CREATE PROCEDURE PRC_CLIENTES_INS
	@NOME NVARCHAR(100),
	@CPF_CNPJ VARCHAR(14),
	@TELEFONE VARCHAR(11),
	@ENDERECO NVARCHAR(255),
	@BAIRRO NVARCHAR(100),
	@COMPLEMENTO NVARCHAR(50),
	@EMAIL NVARCHAR(50),
	@COD_CIDADE INT,
	@CEP char(8),
	@CODIGO INT OUTPUT
AS
BEGIN
	BEGIN TRANSACTION
	
	BEGIN TRY
		IF @CEP = ''
		BEGIN
			RAISERROR('CEP NAO INFORMADO !', 16,1);
		END

		IF @NOME = ''
		BEGIN
			RAISERROR('NOME CLIENTE NAO INFORMADO !', 16,1);
		END

		IF @CPF_CNPJ = ''
		BEGIN
			RAISERROR('CPF/CNPJ CLIENTE NAO INFORMADO !', 16,1);
		END

		INSERT INTO CLIENTES (CPF_CNPJ, NOME, ENDERECO, BAIRRO, COMPLEMENTO, EMAIL, TELEFONE, COD_CIDADE, CEP) 
		VALUES (@CPF_CNPJ, @NOME, @ENDERECO,@BAIRRO, @COMPLEMENTO, @EMAIL, @TELEFONE, @COD_CIDADE, @CEP);

		SET @CODIGO = SCOPE_IDENTITY();

		COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END;

GO

CREATE PROCEDURE PRC_CLIENTES_UPD
	@COD_CLIENTE INT,
	@NOME NVARCHAR(100),
	@CPF_CNPJ VARCHAR(14),
	@TELEFONE VARCHAR(11),
	@ENDERECO NVARCHAR(255),
	@BAIRRO NVARCHAR(100),
	@COMPLEMENTO NVARCHAR(50),
	@EMAIL NVARCHAR(50),
	@COD_CIDADE INT,
	@CEP CHAR(8)
AS
BEGIN
	DECLARE @CLIENTE_TESTE INT;
	DECLARE @CIDADE_TESTE INT;


	SELECT @CLIENTE_TESTE = CODIGO FROM CLIENTES WHERE CLIENTES.CODIGO = @COD_CLIENTE
	SELECT @CIDADE_TESTE = CODIGO FROM CIDADES WHERE CIDADES.CODIGO = @COD_CIDADE

	BEGIN TRANSACTION
	
	BEGIN TRY

		IF @CLIENTE_TESTE = 0 
		BEGIN
			RAISERROR('CLIENTE NAO ENCONTRADO !', 16,1);
		END

		IF @CIDADE_TESTE = 0 
		BEGIN
			RAISERROR('CIDADE NÃO ENCONTRADA !', 16,1);
		END

		IF @NOME = ''
		BEGIN
			RAISERROR('NOME CLIENTE NAO INFORMADO !', 16,1);
		END

		IF @CPF_CNPJ = ''
		BEGIN
			RAISERROR('CPF/CNPJ CLIENTE NAO INFORMADO !', 16,1);
		END

		UPDATE  CLIENTES SET 
			CPF_CNPJ = @CPF_CNPJ, 
			NOME = @NOME, 
			ENDERECO = @ENDERECO, 
			BAIRRO= @BAIRRO, 
			COMPLEMENTO = @COMPLEMENTO, 
			EMAIL = @EMAIL,
			TELEFONE = @TELEFONE, 
			COD_CIDADE= @COD_CIDADE,
			CEP = @CEP
		WHERE CODIGO = @COD_CLIENTE

		COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END;
GO 

CREATE PROCEDURE PRC_CLIENTES_DEL 
	@COD_CLIENTE INT
AS
BEGIN
	BEGIN TRANSACTION
	
	BEGIN TRY
		DECLARE @CLIENTE_TESTE INT;

		SELECT @CLIENTE_TESTE = CODIGO FROM CLIENTES WHERE CLIENTES.CODIGO = @COD_CLIENTE

		IF @CLIENTE_TESTE = 0 
		BEGIN
			RAISERROR('CLIENTE NAO ENCONTRADO !', 16,1);
		END

		DELETE  FROM CLIENTES WHERE CODIGO = @CLIENTE_TESTE; 

		COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END;