USE EVERTEC
GO

CREATE PROCEDURE PRC_CIDADES_INS
	@NOME NVARCHAR(100),
	@ESTADO CHAR(2),
	@CEP_INICIAL CHAR(8),
	@CEP_FINAL CHAR(8),
	@CODIGO INT OUTPUT
AS
BEGIN
	BEGIN TRANSACTION
	
	BEGIN TRY
		IF @NOME = ''
		BEGIN
			RAISERROR('NOME CIDADE NAO INFORMADO !', 16,1);
		END

		IF @ESTADO = ''
		BEGIN
			RAISERROR('ESTADO NAO INFORMADO !', 16,1);
		END

		IF @CEP_INICIAL = ''
		BEGIN
			RAISERROR('CEP INICIAL NAO INFORMADO !', 16,1);
		END

		IF @CEP_FINAL = ''
		BEGIN
			RAISERROR('CEP FINAL NAO INFORMADO !', 16,1);
		END

		INSERT INTO CIDADES (NOME, ESTADO,CEP_INICIAL, CEP_FINAL) 
		VALUES (@NOME,@ESTADO, @CEP_INICIAL, @CEP_FINAL);

		SET @CODIGO = SCOPE_IDENTITY();

		COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH	
END;
GO

CREATE PROCEDURE PRC_CIDADES_UPD
	@COD_CIDADE INT,
	@NOME NVARCHAR(100),
	@ESTADO CHAR(2),
	@CEP_INICIAL CHAR(8),
	@CEP_FINAL CHAR(8)
AS
BEGIN
	BEGIN TRANSACTION

	DECLARE @CIDADE_TESTE INT;

	SELECT @CIDADE_TESTE = CODIGO FROM CIDADES WHERE CODIGO = @COD_CIDADE;
	
	BEGIN TRY
		IF @CIDADE_TESTE = ''
		BEGIN
			RAISERROR('CIDADE NAO ENCONTRADA!', 16,1);
		END


		IF @NOME = ''
		BEGIN
			RAISERROR('NOME CIDADE NAO INFORMADO !', 16,1);
		END

		IF @ESTADO = ''
		BEGIN
			RAISERROR('ESTADO NAO INFORMADO !', 16,1);
		END

		IF @CEP_INICIAL = ''
		BEGIN
			RAISERROR('CEP INICIAL NAO INFORMADO !', 16,1);
		END

		IF @CEP_FINAL = ''
		BEGIN
			RAISERROR('CEP FINAL NAO INFORMADO !', 16,1);
		END

		UPDATE CIDADES SET 
			NOME = @NOME, 
			ESTADO = @ESTADO,
			CEP_INICIAL = @CEP_INICIAL, 
			CEP_FINAL = @CEP_FINAL 
		WHERE CODIGO = @COD_CIDADE;

		COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

	END CATCH	
END;
GO

CREATE PROCEDURE PRC_CIDADES_DEL
	@COD_CIDADE INT
AS
BEGIN
	BEGIN TRANSACTION

	DECLARE @CIDADE_TESTE INT;

	SELECT @CIDADE_TESTE = CODIGO FROM CIDADES WHERE CODIGO = @COD_CIDADE;
	
	BEGIN TRY
		IF @CIDADE_TESTE = ''
		BEGIN
			RAISERROR('CIDADE NAO ENCONTRADA!', 16,1);
		END

		DELETE FROM CIDADES
		WHERE CODIGO = @COD_CIDADE;

		COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH	
END;